package project.DO;
// Generated Sep 25, 2016 1:03:51 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name="course"
    ,catalog="mydb"
)
public class Course  implements java.io.Serializable {


     private Integer idcourse;
     private String courseName;
     private String image;
     private String createDate;
     private String field;
     private String column1;
     private String column2;
     private String column3;

    public Course() {
    }

	
    public Course(String courseName, String image, String createDate) {
        this.courseName = courseName;
        this.image = image;
        this.createDate = createDate;
    }
    public Course(String courseName, String image, String createDate, String field, String column1, String column2, String column3) {
       this.courseName = courseName;
       this.image = image;
       this.createDate = createDate;
       this.field = field;
       this.column1 = column1;
       this.column2 = column2;
       this.column3 = column3;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcourse", unique=true, nullable=false)
    public Integer getIdcourse() {
        return this.idcourse;
    }
    
    public void setIdcourse(Integer idcourse) {
        this.idcourse = idcourse;
    }

    
    @Column(name="course_name", nullable=false, length=100)
    public String getCourseName() {
        return this.courseName;
    }
    
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    
    @Column(name="image", nullable=false, length=100)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }

    
    @Column(name="create_date", nullable=false, length=45)
    public String getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="field", length=45)
    public String getField() {
        return this.field;
    }
    
    public void setField(String field) {
        this.field = field;
    }

    
    @Column(name="column1", length=45)
    public String getColumn1() {
        return this.column1;
    }
    
    public void setColumn1(String column1) {
        this.column1 = column1;
    }

    
    @Column(name="column2", length=45)
    public String getColumn2() {
        return this.column2;
    }
    
    public void setColumn2(String column2) {
        this.column2 = column2;
    }

    
    @Column(name="column3", length=45)
    public String getColumn3() {
        return this.column3;
    }
    
    public void setColumn3(String column3) {
        this.column3 = column3;
    }




}


