package project.DO;
// Generated Sep 11, 2016 4:47:28 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CourseAccount generated by hbm2java
 */
@Entity
@Table(name="course_account"
    ,catalog="mydb"
)
public class CourseAccount  implements java.io.Serializable {


     private Integer id;
     private int idAccountUse;
     private int idAccountCreate;
     private int idCource;

    public CourseAccount() {
    }

    public CourseAccount(int idAccountUse, int idAccountCreate, int idCource) {
       this.idAccountUse = idAccountUse;
       this.idAccountCreate = idAccountCreate;
       this.idCource = idCource;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="id_account_use", nullable=false)
    public int getIdAccountUse() {
        return this.idAccountUse;
    }
    
    public void setIdAccountUse(int idAccountUse) {
        this.idAccountUse = idAccountUse;
    }

    
    @Column(name="id_account_create", nullable=false)
    public int getIdAccountCreate() {
        return this.idAccountCreate;
    }
    
    public void setIdAccountCreate(int idAccountCreate) {
        this.idAccountCreate = idAccountCreate;
    }

    
    @Column(name="id_cource", nullable=false)
    public int getIdCource() {
        return this.idCource;
    }
    
    public void setIdCource(int idCource) {
        this.idCource = idCource;
    }




}


