-- MySQL Script generated by MySQL Workbench
-- 09/11/16 04:39:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`account` (
  `idaccount` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `account_name` VARCHAR(100) NOT NULL,
  `create_date` DATETIME NOT NULL,
  PRIMARY KEY (`idaccount`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`account_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`account_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `school` VARCHAR(100) NULL,
  `class` VARCHAR(100) NULL,
  `address` VARCHAR(200) NULL,
  `account_infocol` VARCHAR(45) NULL,
  `id_account` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cource_name` VARCHAR(100) NOT NULL,
  `cource_image` VARCHAR(100) NOT NULL,
  `cource_create_date` VARCHAR(100) NOT NULL,
  `field` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lesson` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lesson_name` VARCHAR(100) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `content` TEXT NOT NULL,
  `create_date` VARCHAR(100) NOT NULL,
  `update_date` VARCHAR(100) NULL,
  `id_cource` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`file` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `src` VARCHAR(100) NOT NULL,
  `size` VARCHAR(100) NOT NULL,
  `title` VARCHAR(100) NULL,
  `type` VARCHAR(100) NOT NULL,
  `create_date` VARCHAR(100) NOT NULL,
  `id_lesson` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `species` VARCHAR(100) NOT NULL,
  `id_out_key` INT NOT NULL,
  `create_date` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`manage_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`manage_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_father` INT NOT NULL,
  `level` INT NOT NULL,
  `index` VARCHAR(45) NOT NULL,
  `id_lesson` INT NOT NULL,
  `id_manage` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`manage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`manage` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_account_create` INT NULL,
  `id_account_use` INT NULL,
  `create_date` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course_account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_account_use` INT NOT NULL,
  `id_account_create` INT NOT NULL,
  `id_cource` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
