package project.DO;
// Generated Sep 25, 2016 1:03:51 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AccountInfo generated by hbm2java
 */
@Entity
@Table(name="account_info"
    ,catalog="mydb"
)
public class AccountInfo  implements java.io.Serializable {


     private Integer idaccountInfo;
     private String firstName;
     private String lastName;
     private String school;
     private String mssv;
     private String class_;
     private String address;
     private int idAccount;
     private String column1;
     private String column2;
     private String column3;

    public AccountInfo() {
    }

	
    public AccountInfo(String firstName, String lastName, String school, int idAccount) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.school = school;
        this.idAccount = idAccount;
    }
    public AccountInfo(String firstName, String lastName, String school, String mssv, String class_, String address, int idAccount, String column1, String column2, String column3) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.school = school;
       this.mssv = mssv;
       this.class_ = class_;
       this.address = address;
       this.idAccount = idAccount;
       this.column1 = column1;
       this.column2 = column2;
       this.column3 = column3;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idaccount_info", unique=true, nullable=false)
    public Integer getIdaccountInfo() {
        return this.idaccountInfo;
    }
    
    public void setIdaccountInfo(Integer idaccountInfo) {
        this.idaccountInfo = idaccountInfo;
    }

    
    @Column(name="first_name", nullable=false, length=100)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", nullable=false, length=100)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="school", nullable=false, length=100)
    public String getSchool() {
        return this.school;
    }
    
    public void setSchool(String school) {
        this.school = school;
    }

    
    @Column(name="MSSV", length=100)
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }

    
    @Column(name="class", length=100)
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }

    
    @Column(name="address", length=100)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="id_account", nullable=false)
    public int getIdAccount() {
        return this.idAccount;
    }
    
    public void setIdAccount(int idAccount) {
        this.idAccount = idAccount;
    }

    
    @Column(name="column1", length=45)
    public String getColumn1() {
        return this.column1;
    }
    
    public void setColumn1(String column1) {
        this.column1 = column1;
    }

    
    @Column(name="column2", length=45)
    public String getColumn2() {
        return this.column2;
    }
    
    public void setColumn2(String column2) {
        this.column2 = column2;
    }

    
    @Column(name="column3", length=45)
    public String getColumn3() {
        return this.column3;
    }
    
    public void setColumn3(String column3) {
        this.column3 = column3;
    }




}


