package project.DO;
// Generated Sep 11, 2016 4:47:28 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name="comment"
    ,catalog="mydb"
)
public class Comment  implements java.io.Serializable {


     private Integer id;
     private String content;
     private String species;
     private int idOutKey;
     private String createDate;

    public Comment() {
    }

	
    public Comment(String content, String species, int idOutKey) {
        this.content = content;
        this.species = species;
        this.idOutKey = idOutKey;
    }
    public Comment(String content, String species, int idOutKey, String createDate) {
       this.content = content;
       this.species = species;
       this.idOutKey = idOutKey;
       this.createDate = createDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="content", nullable=false, length=65535)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    
    @Column(name="species", nullable=false, length=100)
    public String getSpecies() {
        return this.species;
    }
    
    public void setSpecies(String species) {
        this.species = species;
    }

    
    @Column(name="id_out_key", nullable=false)
    public int getIdOutKey() {
        return this.idOutKey;
    }
    
    public void setIdOutKey(int idOutKey) {
        this.idOutKey = idOutKey;
    }

    
    @Column(name="create_date", length=100)
    public String getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }




}


