package project.DO;
// Generated Sep 11, 2016 4:47:28 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name="course"
    ,catalog="mydb"
)
public class Course  implements java.io.Serializable {


     private Integer id;
     private String courceName;
     private String courceImage;
     private String courceCreateDate;
     private String field;

    public Course() {
    }

	
    public Course(String courceName, String courceImage, String courceCreateDate) {
        this.courceName = courceName;
        this.courceImage = courceImage;
        this.courceCreateDate = courceCreateDate;
    }
    public Course(String courceName, String courceImage, String courceCreateDate, String field) {
       this.courceName = courceName;
       this.courceImage = courceImage;
       this.courceCreateDate = courceCreateDate;
       this.field = field;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="cource_name", nullable=false, length=100)
    public String getCourceName() {
        return this.courceName;
    }
    
    public void setCourceName(String courceName) {
        this.courceName = courceName;
    }

    
    @Column(name="cource_image", nullable=false, length=100)
    public String getCourceImage() {
        return this.courceImage;
    }
    
    public void setCourceImage(String courceImage) {
        this.courceImage = courceImage;
    }

    
    @Column(name="cource_create_date", nullable=false, length=100)
    public String getCourceCreateDate() {
        return this.courceCreateDate;
    }
    
    public void setCourceCreateDate(String courceCreateDate) {
        this.courceCreateDate = courceCreateDate;
    }

    
    @Column(name="field", length=100)
    public String getField() {
        return this.field;
    }
    
    public void setField(String field) {
        this.field = field;
    }




}


