package project.DO;
// Generated Sep 11, 2016 4:47:28 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ManageInfo generated by hbm2java
 */
@Entity
@Table(name="manage_info"
    ,catalog="mydb"
)
public class ManageInfo  implements java.io.Serializable {


     private Integer id;
     private int idFather;
     private int level;
     private String index;
     private int idLesson;
     private int idManage;

    public ManageInfo() {
    }

    public ManageInfo(int idFather, int level, String index, int idLesson, int idManage) {
       this.idFather = idFather;
       this.level = level;
       this.index = index;
       this.idLesson = idLesson;
       this.idManage = idManage;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="id_father", nullable=false)
    public int getIdFather() {
        return this.idFather;
    }
    
    public void setIdFather(int idFather) {
        this.idFather = idFather;
    }

    
    @Column(name="level", nullable=false)
    public int getLevel() {
        return this.level;
    }
    
    public void setLevel(int level) {
        this.level = level;
    }

    
    @Column(name="index", nullable=false, length=45)
    public String getIndex() {
        return this.index;
    }
    
    public void setIndex(String index) {
        this.index = index;
    }

    
    @Column(name="id_lesson", nullable=false)
    public int getIdLesson() {
        return this.idLesson;
    }
    
    public void setIdLesson(int idLesson) {
        this.idLesson = idLesson;
    }

    
    @Column(name="id_manage", nullable=false)
    public int getIdManage() {
        return this.idManage;
    }
    
    public void setIdManage(int idManage) {
        this.idManage = idManage;
    }




}


