package project.DO;
// Generated Sep 11, 2016 4:47:28 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * File generated by hbm2java
 */
@Entity
@Table(name="file"
    ,catalog="mydb"
)
public class File  implements java.io.Serializable {


     private Integer id;
     private String src;
     private String size;
     private String title;
     private String type;
     private String createDate;
     private Integer idLesson;

    public File() {
    }

	
    public File(String src, String size, String type, String createDate) {
        this.src = src;
        this.size = size;
        this.type = type;
        this.createDate = createDate;
    }
    public File(String src, String size, String title, String type, String createDate, Integer idLesson) {
       this.src = src;
       this.size = size;
       this.title = title;
       this.type = type;
       this.createDate = createDate;
       this.idLesson = idLesson;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="src", nullable=false, length=100)
    public String getSrc() {
        return this.src;
    }
    
    public void setSrc(String src) {
        this.src = src;
    }

    
    @Column(name="size", nullable=false, length=100)
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }

    
    @Column(name="title", length=100)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="type", nullable=false, length=100)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="create_date", nullable=false, length=100)
    public String getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="id_lesson")
    public Integer getIdLesson() {
        return this.idLesson;
    }
    
    public void setIdLesson(Integer idLesson) {
        this.idLesson = idLesson;
    }




}


