package project.DO;
// Generated Sep 11, 2016 4:47:28 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Manage generated by hbm2java
 */
@Entity
@Table(name="manage"
    ,catalog="mydb"
)
public class Manage  implements java.io.Serializable {


     private Integer id;
     private Integer idAccountCreate;
     private Integer idAccountUse;
     private String createDate;

    public Manage() {
    }

    public Manage(Integer idAccountCreate, Integer idAccountUse, String createDate) {
       this.idAccountCreate = idAccountCreate;
       this.idAccountUse = idAccountUse;
       this.createDate = createDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="id_account_create")
    public Integer getIdAccountCreate() {
        return this.idAccountCreate;
    }
    
    public void setIdAccountCreate(Integer idAccountCreate) {
        this.idAccountCreate = idAccountCreate;
    }

    
    @Column(name="id_account_use")
    public Integer getIdAccountUse() {
        return this.idAccountUse;
    }
    
    public void setIdAccountUse(Integer idAccountUse) {
        this.idAccountUse = idAccountUse;
    }

    
    @Column(name="create_date", length=100)
    public String getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }




}


